#!/usr/bin/env python3
"""Refresh VitePress reference pages and downloads from repository documentation."""
from pathlib import Path
import argparse
import re
from html import escape
import shutil

ROOT = Path(__file__).resolve().parents[1]
SITE = ROOT / 'docs/site'
PUBLIC = SITE / 'public'
# Keep these exact paths in docs/site/.gitignore; authored pages must survive cleanup.
GENERATED_PAGES = (
    'get-started/install.md',
    'get-started/first-run.md',
    'reference/command-line.md',
    'reference/configuration.md',
    'configure/logging.md',
    'reference/helpers.md',
    'operate/troubleshooting.md',
    'understand/compatibility.md',
    'history/performance.md',
    'history/logging.md',
    'history/appearance.md',
    'develop/testing.md',
    'project/authors.md',
    'project/license.md',
)
ROUTES = {
    'README.md': '/get-started/install',
    'docs/qtalh-user-guide.md': '/get-started/first-run',
    'docs/qtalh-compatibility.md': '/understand/compatibility',
    'docs/qtalh-performance.md': '/history/performance',
    'docs/qtalh-logging-analysis.md': '/history/logging',
    'docs/qtalh-appearance.md': '/history/appearance',
    'qtalh/tests/README.md': '/develop/testing',
    'AUTHORS.md': '/project/authors',
    'LICENSE': '/project/license',
    'alh/documentation/ALH.html': '/legacy/ALH.html',
}
SECTIONS = {
    'first-run': '/get-started/first-run',
    'command-line-reference': '/reference/command-line',
    'configuration-format': '/reference/configuration',
    'logging-and-shared-operation': '/configure/logging',
    'troubleshooting': '/operate/troubleshooting',
}

def read(name):
    return (ROOT / name).read_text()


def section(source, heading, level=2):
    marker = '#' * level + ' ' + heading + '\n'
    body = source.split(marker, 1)[1]
    return re.split(r'\n#{1,' + str(level) + r'} ', body, maxsplit=1)[0].strip() + '\n'


def download(path):
    target = PUBLIC / 'downloads' / path.relative_to(ROOT)
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(path, target)
    return '/downloads/' + path.relative_to(ROOT).as_posix()


def rewrite(text, origin):
    def link(match):
        label, target = match.groups()
        if re.match(r'^[a-zA-Z]+:', target) or target.startswith(('#', '/')):
            return match.group(0)
        name, sep, anchor = target.partition('#')
        source = (ROOT / origin).parent / name
        source = source.resolve()
        key = source.relative_to(ROOT).as_posix()
        if key == 'README.md' and anchor in ('validation', 'architecture-and-compatibility', 'authors-and-acknowledgements'):
            route = {'validation': '/develop/testing', 'architecture-and-compatibility': '/develop/architecture',
                     'authors-and-acknowledgements': '/project/authors'}[anchor]
            anchor = ''
        elif key == 'docs/qtalh-user-guide.md' and anchor in SECTIONS:
            route, anchor = SECTIONS[anchor], ''
        else:
            route = ROUTES.get(key)
            if route is None:
                if not source.is_file():
                    raise FileNotFoundError(f'{origin}: {target}')
                route = download(source)
            if key == 'README.md' and anchor == 'build-and-run':
                anchor = ''
        if route.startswith('/legacy/'):
            href = route + ('#' + anchor if anchor else '')
            return f'<a href="{escape(href, quote=True)}" target="_self">{escape(label)}</a>'
        if route.startswith('/downloads/'):
            return f'<a href="{escape(route, quote=True)}" download>{escape(label)}</a>'
        return f'[{label}]({route}' + ('#' + anchor if anchor else '') + ')'
    return re.sub(r'\[([^\]]*)\]\(([^)]+)\)', link, text)


def write(route, title, content, origin):
    relative = route.lstrip('/') + '.md'
    if relative not in GENERATED_PAGES:
        raise ValueError(f'Register generated page for cleanup and gitignore: {relative}')
    path = SITE / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    # VitePress's automatic next-page control drops sidebar link targets.
    # The final modern history page must not route into the standalone archive.
    metadata = '---\nnext: false\n---\n\n' if route == '/history/appearance' else ''
    path.write_text(metadata + '<!-- Generated by scripts/sync-docs.py; edit the source document. -->\n\n'
                    + '# ' + title + '\n\n' + rewrite(content.strip(), origin) + '\n')


def clean(distclean=False):
    paths = [SITE / name for name in GENERATED_PAGES]
    paths += [PUBLIC / 'downloads', PUBLIC / 'legacy', SITE / '.vitepress/cache',
              SITE / 'dist', ROOT / 'docs/html']
    if distclean:
        paths.append(SITE / 'node_modules')
    for path in paths:
        if path.is_symlink() or path.is_file():
            path.unlink()
        elif path.is_dir():
            shutil.rmtree(path)
    print('Removed generated documentation' + (' and dependencies.' if distclean else '.'))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    modes = parser.add_mutually_exclusive_group()
    modes.add_argument('--clean', action='store_true', help='Remove generated documentation; preserve sources and dependencies')
    modes.add_argument('--distclean', action='store_true', help='Also remove installed documentation dependencies')
    args = parser.parse_args()
    if args.clean or args.distclean:
        clean(distclean=args.distclean)
        return
    guide = read('docs/qtalh-user-guide.md')
    readme = read('README.md')
    install = section(readme, 'Build and run')
    write('/get-started/install', 'Install & build QtALH',
          'Choose your platform: [Linux and macOS](#linux-and-macos) · [Windows](#windows).\n\n' + install, 'README.md')
    for heading, route, title in [
        ('First run', '/get-started/first-run', 'Open your first configuration'),
        ('Command-line reference', '/reference/command-line', 'Command-line options'),
        ('Configuration format', '/reference/configuration', 'Configuration format'),
    ]:
        write(route, title, section(guide, heading), 'docs/qtalh-user-guide.md')
    logging = section(guide, 'Logging and shared operation')
    logging, helpers = logging.split('Linux/macOS helpers retain these positional arguments:', 1)
    write('/configure/logging', 'Logging & shared operation', logging, 'docs/qtalh-user-guide.md')
    write('/reference/helpers', 'Helper programs',
          'Linux/macOS helpers retain these positional arguments:' + helpers, 'docs/qtalh-user-guide.md')
    troubleshooting = section(guide, 'Troubleshooting').split('For developer orientation,', 1)[0]
    write('/operate/troubleshooting', 'Troubleshooting', troubleshooting, 'docs/qtalh-user-guide.md')
    for source, route, title in [
        ('docs/qtalh-compatibility.md', '/understand/compatibility', 'Compatibility & validation'),
        ('docs/qtalh-performance.md', '/history/performance', 'CPU benchmarks'),
        ('docs/qtalh-logging-analysis.md', '/history/logging', 'Logging investigation'),
        ('docs/qtalh-appearance.md', '/history/appearance', 'Appearance comparisons'),
        ('qtalh/tests/README.md', '/develop/testing', 'Tests & contributions'),
        ('AUTHORS.md', '/project/authors', 'Authors & acknowledgements'),
    ]:
        body = read(source).split('\n', 1)[1]
        if route.startswith('/history/'):
            body = ('::: info Historical engineering record\nThese measurements and observations describe the dated '
                    'workloads in this record. They are not current performance guarantees.\n:::\n\n' + body)
        if route == '/develop/testing':
            body += ('\n## Preparing a contribution\n\nKeep changes focused and retain source provenance and the original license. '
                     'Run the suites relevant to changed behavior and report the platform, Qt/EPICS versions, '
                     'results, and unavailable checks. Update affected guides and configuration examples. '
                     'See [Maintaining these docs](/develop/documentation) for the documentation workflow.\n')
        write(route, title, body, source)
    write('/project/license', 'License',
          'The original ALH license is reproduced below. Existing source-file copyright notices remain in place.\n\n'
          + '```text\n' + read('LICENSE').rstrip() + '\n```\n', 'LICENSE')
    for name in ['examples/minimal.alhConfig', 'examples/tutorial.alhConfig', 'examples/tutorial.db']:
        if (ROOT / name).is_file():
            download(ROOT / name)
    # Preserve the self-contained historical HTML manual and its local images.
    shutil.copytree(ROOT / 'alh/documentation', PUBLIC / 'legacy', dirs_exist_ok=True)
    (PUBLIC / 'legacy/README.txt').write_text('Historical ALH manual. For QtALH behavior, use the modern guides and compatibility inventory.\n')
    print('Refreshed reference pages, original manual, and linked downloads.')


if __name__ == '__main__':
    main()
